#!/bin/bash

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";


if [ $# -eq 0 ] 
then
	node $SCRIPT_DIR/holyc-interpreter-cli.js idle
else
	node $SCRIPT_DIR/holyc-interpreter-cli.js scan "$(cat $1)"
fi
